all:
	@$(MAKE) -C libio --no-print-directory
	@$(MAKE) -C liblv2 --no-print-directory
	@$(MAKE) -C liblv2dbg --no-print-directory
	@$(MAKE) -C libnet --no-print-directory
	@$(MAKE) -C libnetctl --no-print-directory
	@$(MAKE) -C libgem --no-print-directory
	@$(MAKE) -C libcamera --no-print-directory
	@$(MAKE) -C libaudio --no-print-directory
	@$(MAKE) -C libpngdec --no-print-directory
	@$(MAKE) -C libjpgdec --no-print-directory
	@$(MAKE) -C libgcm_sys --no-print-directory
	@$(MAKE) -C libresc --no-print-directory
	@$(MAKE) -C libssl --no-print-directory
	@$(MAKE) -C libhttp --no-print-directory
	@$(MAKE) -C libhttputil --no-print-directory
	@$(MAKE) -C libsysfs --no-print-directory
	@$(MAKE) -C libsysutil --no-print-directory
	@$(MAKE) -C libsysmodule --no-print-directory
	@$(MAKE) -C libvdec --no-print-directory
	@$(MAKE) -C libusb --no-print-directory
	@$(MAKE) -C libspurs --no-print-directory
	
install:
	@$(MAKE) -C libio install --no-print-directory
	@$(MAKE) -C liblv2 install --no-print-directory
	@$(MAKE) -C liblv2dbg install --no-print-directory
	@$(MAKE) -C libnet install --no-print-directory
	@$(MAKE) -C libnetctl install --no-print-directory
	@$(MAKE) -C libgem install --no-print-directory
	@$(MAKE) -C libcamera install --no-print-directory
	@$(MAKE) -C libaudio install --no-print-directory
	@$(MAKE) -C libpngdec install --no-print-directory
	@$(MAKE) -C libjpgdec install --no-print-directory
	@$(MAKE) -C libgcm_sys install --no-print-directory
	@$(MAKE) -C libresc install --no-print-directory
	@$(MAKE) -C libssl install --no-print-directory
	@$(MAKE) -C libhttp install --no-print-directory
	@$(MAKE) -C libhttputil install --no-print-directory
	@$(MAKE) -C libsysfs install --no-print-directory
	@$(MAKE) -C libsysutil install --no-print-directory
	@$(MAKE) -C libsysmodule install --no-print-directory
	@$(MAKE) -C libvdec install --no-print-directory
	@$(MAKE) -C libusb install --no-print-directory
	@$(MAKE) -C libspurs install --no-print-directory
	
clean:
	@$(MAKE) -C libio clean --no-print-directory
	@$(MAKE) -C liblv2 clean --no-print-directory
	@$(MAKE) -C liblv2dbg clean --no-print-directory
	@$(MAKE) -C libnet clean --no-print-directory
	@$(MAKE) -C libnetctl clean --no-print-directory
	@$(MAKE) -C libgem clean --no-print-directory
	@$(MAKE) -C libcamera clean --no-print-directory
	@$(MAKE) -C libaudio clean --no-print-directory
	@$(MAKE) -C libpngdec clean --no-print-directory
	@$(MAKE) -C libjpgdec clean --no-print-directory
	@$(MAKE) -C libgcm_sys clean --no-print-directory
	@$(MAKE) -C libresc clean --no-print-directory
	@$(MAKE) -C libssl clean --no-print-directory
	@$(MAKE) -C libhttp clean --no-print-directory
	@$(MAKE) -C libhttputil clean --no-print-directory
	@$(MAKE) -C libsysfs clean --no-print-directory
	@$(MAKE) -C libsysutil clean --no-print-directory
	@$(MAKE) -C libsysmodule clean --no-print-directory
	@$(MAKE) -C libvdec clean --no-print-directory
	@$(MAKE) -C libusb clean --no-print-directory
	@$(MAKE) -C libspurs  clean --no-print-directory
	
.PHONY: all clean install
